# Generated by Django 4.2.7 on 2025-07-30 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_pet_owner'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='pet',
            index=models.Index(fields=['status', 'pet_type'], name='pets_pet_status_6b94fc_idx'),
        ),
        migrations.AddIndex(
            model_name='pet',
            index=models.Index(fields=['created_at'], name='pets_pet_created_b037d0_idx'),
        ),
    ]
