# Generated by Django 5.2.4 on 2025-07-27 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0001_initial'),
        ('pets', '0002_pet_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptionrequest',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.pet'),
        ),
        migrations.AlterModelOptions(
            name='adoptionrequest',
            options={'ordering': ['-created']},
        ),
        migrations.AlterField(
            model_name='adoptionrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.DeleteModel(
            name='Pet',
        ),
    ]
