# Generated by Django 4.2.7 on 2025-07-30 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0002_alter_adoptionrequest_pet_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='adoptionrequest',
            index=models.Index(fields=['status', 'created'], name='adoption_ad_status_b454c2_idx'),
        ),
        migrations.AddIndex(
            model_name='adoptionrequest',
            index=models.Index(fields=['user', 'status'], name='adoption_ad_user_id_f03629_idx'),
        ),
    ]
